version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.7-stretch-node
    steps:
      - checkout
      - run:
          name: "Install prerequisites"
          command: |
            bundle config github.https true
            bundle install
            bundle exec rake test_app
      - run:
          name: "Run Test Suite"
          command: |
            bundle exec rake spec
